version: '3'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
  pgweb:
    image: sosedoff/pgweb
    container_name: pgweb
    ports: 
      - "8081:8081"
    environment:
      - DATABASE_URL=postgres://test:test@postgres:5432/testdb?sslmode=disable
    depends_on:
      - postgres
  migrate:
    build:
      context: ./migrate/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./migrate/db/migrations/:/opt/migrate/db/migrations/
    environment:
      - POSTGRESQL_URL=postgres://test:test@postgres:5432/testdb?sslmode=disable
  web-server:
    image: web-server-gin
    build: 
      context: .
      target: runner
    volumes: 
      - ./src/:/opt/myapp/
    working_dir: /opt/myapp/
    ports:
      - 8080:8080
    # command: bash
    # tty: true
    command: go run main.go